# Generated by Django 4.1.3 on 2023-04-17 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='sucessfull',
            new_name='successful',
        ),
    ]
